name: Cleanup Container Registries

on:
  # Run weekly on Sunday at 3 AM UTC
  schedule:
    - cron: '0 3 * * 0'
  # Allow manual trigger from the Actions tab
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run mode (true does not delete, only simulates)'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

# 2. Environment variables available to all jobs in THIS workflow
env:
  DOCKERHUB_SLUG: ${{ secrets.DOCKERHUB_USERNAME }}/mopidy
  GHCR_SLUG: ghcr.io/${{ github.repository_owner }}/mopidy

jobs:
  cleanup:
    name: Run Registry Cleanup
    runs-on: ubuntu-latest
    permissions:
      packages: write # Required for the GHCR cleanup action

    steps:
        # Github action to get branch or tag information
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Clean up Docker Hub
        uses: lostlink/docker-cleanup@v1.0.1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repositories: ${{ env.DOCKERHUB_SLUG }}
          # Custom rule to delete all tags starting with 'test_' older than 30 days
          custom-patterns: |
            {
              "^test_.*": 30
            }
          dry-run: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.dry_run || 'false' }}
          verbose: true

      - name: Clean up GitHub Container Registry (GHCR)
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          # The repository to clean up. Optional, current will be retrieved dyn. from environment.
          # repository: ${{ env.GHCR_SLUG }}
          # Delete all tags starting with 'test_'
          delete-tags: 'test_*'
          # But only if they are older than 30 days
          older-than: '30 days'
          keep-n-untagged: 1
          dry-run: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.dry_run || 'false' }}